# Created by jacob.mendt@pikobytes.de on 13.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Makes sure that previous elasticsearch installations are cleaned up. Use this carefully because
# it also deletes configuration files
  - name: Remove existing elasticsearch
    apt:
      name: [elasticsearch]
      state: absent
      purge: True
    become: yes

  - name: Clean /etc/elasticsearch
    file:
      path: /etc/elasticsearch
      state: absent
    become: yes