# Created by jacob.mendt@pikobytes.de on 13.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Installation and configuration of the elasticsearch
#  * Ensure java is installed
#  * Install elasticsearch and add as system service
#  * Configure default password for user "elastic"
---
  - name: Upgrade all packages to latest version (dist-upgrade)
    apt:
      upgrade: dist
      update_cache: yes
    become: yes

  - name: Ensure headless JRE and gnupg is installed
    apt:
      name: [openjdk-11-jre-headless, gnupg]
    become: yes

  - name: Add Elasticsearch apt key
    apt_key:
      url: https://packages.elastic.co/GPG-KEY-elasticsearch
      state: present
    become: yes

  - name: Add Elasticsearch repository
    apt_repository:
      repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
      state: present
      update_cache: yes
    become: yes

  - name: Install Elasticsearch
    package:
      name: elasticsearch
      state: present
    become: yes

  - template:
      src: elasticsearch.j2
      dest: /etc/default/elasticsearch
      owner: root
      group: elasticsearch
      mode: "u=rw,g=r"
    become: yes

  - template:
      src: elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: root
      group: elasticsearch
      mode: "u=rw,g=r"
    become: yes

  - name: Reload systemd
    shell: sudo /bin/systemctl daemon-reload

  - name: Add Elasticsearch to systemd
    shell: sudo /bin/systemctl enable elasticsearch.service

  # Create Bootstrap User / Password
  - name: Check if bootstrap password is set
    command: >
     {{es.es_home}}/bin/elasticsearch-keystore list
    register: list_keystore
    changed_when: False
    become: yes

  - name: Create Bootstrap password for elastic user
    shell: echo "{{es.es_api_basic_auth_password}}" | {{es.es_home}}/bin/elasticsearch-keystore add -x 'bootstrap.password'
    when:
      - es.es_api_basic_auth_username is defined and list_keystore is defined and es.es_api_basic_auth_username == 'elastic' and 'bootstrap.password' not in list_keystore.stdout_lines
    become: yes

  # Start the service
  - name: Start Elasticsearch
    shell: sudo systemctl start elasticsearch.service