# Created by jacob.mendt@pikobytes.de on 13.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Installation and configuration of the elasticsearch
#  * Ensure java is installed
#  * Installs latest elasticsearch
#  * Enables elasticsearch as systemctl service
#  * Sets elasticsearch password
---
  - include_tasks:
      file: clean-es.yml
    when: es.always_reset == True

  - name: Upgrade all packages to latest version (dist-upgrade)
    apt:
      upgrade: dist
      update_cache: yes
    become: yes

  - name: Ensure headless JRE and gnupg is installed
    apt:
      name: [openjdk-11-jre-headless, gnupg]
    become: yes

  - name: Flush handlers
    meta: flush_handlers

  - name: Add Elasticsearch apt key
    get_url:
      url: https://packages.elastic.co/GPG-KEY-elasticsearch
      dest: /usr/share/keyrings/elasticsearch-archive-keyring.asc
    become: yes

  - name: Flush handlers
    meta: flush_handlers

  - name: Add Elasticsearch repository
    copy:
      dest: /etc/apt/sources.list.d/elasticsearch.list
      content: >
         deb [arch=amd64 signed-by=/usr/share/keyrings/elasticsearch-archive-keyring.asc] https://artifacts.elastic.co/packages/7.x/apt stable main
    become: yes
    notify: update_apt_cache

  - name: Add Elasticsearch to unattended-upgrades
    copy:
      dest: /etc/apt/apt.conf.d/90unattended-upgrades-elasticsearch
      content: |
         Unattended-Upgrade::Origins-Pattern {
           "origin=elastic,codename=stable";
         };
    become: yes

  - name: Install Elasticsearch
    package:
      name: elasticsearch
      state: present
    become: yes

  - template:
      src: elasticsearch.j2
      dest: /etc/default/elasticsearch
      owner: root
      group: elasticsearch
      mode: "u=rw,g=r"
    become: yes

  - template:
      src: elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: root
      group: elasticsearch
      mode: "u=rw,g=r"
    become: yes

  - name: Reload systemd
    shell: /bin/systemctl daemon-reload
    become: yes

  - name: Add Elasticsearch to systemd
    shell: /bin/systemctl enable elasticsearch.service
    become: yes

  # Create Bootstrap User / Password
  - name: Check if bootstrap password is set
    command: >
     {{es.es_home}}/bin/elasticsearch-keystore list
    register: list_keystore
    changed_when: False
    become: yes

  - name: Create Bootstrap password for elastic user
    shell: echo "{{es.es_api_basic_auth_password}}" | {{es.es_home}}/bin/elasticsearch-keystore add -x 'bootstrap.password'
    when:
      - es.es_api_basic_auth_username is defined and list_keystore is defined and es.es_api_basic_auth_username == 'elastic' and 'bootstrap.password' not in list_keystore.stdout_lines
    become: yes

  # Start the service
  - name: Start Elasticsearch
    shell: systemctl start elasticsearch.service
    become: yes