# Created by jacob.mendt@pikobytes.de on 26.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# This task makes sure that georeference service and daemon are not running.
---
  # At start check if there is already a service running on the system
  - name: Stop service if running
    service:
      name: georeference.service
      state: stopped
    become: yes

  # At start check if there is already a running daemon and stop him
  - name: Check if there is a running georeference daemon
    shell: "ps -ef | grep -v grep | grep -w {{ service.root_path }}/georeference/daemon/runner.py | awk '{print $2}'"
    register: running_daemon

  - name: Kill running daemon process
    shell: "kill -9 {{ item }}"
    with_items: "{{ running_daemon.stdout_lines }}"
