# Created by jacob.mendt@pikobytes.de on 13.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Installs a standalone tile server with initial configuration and an Apache2 HTTP server as reverse proxy and
# an image cache.
---
- hosts: all
  vars:
    apache2:
      admin_mail: info@pikobytes.de
      vhosts:
        - name: 111.111.111.111
    tileserver_gl:
      root_dir: /opt/tileserver
      mbtile: zurich_switzerland.mbtiles
      mbtile_download_link: https://tile-1.pikobytes.de/zurich_switzerland.mbtiles
      mbtile_bounds: [8.3613,47.2958,8.6744,47.4854]
      tile_domains:
        - name: 111.111.111.111
    disk_cache_size: 10G
    custom_remote_user: vk2adm
  remote_user: vk2adm
  roles:
    - tileserver-gl
    - apache-http