# Created by jacob.mendt@pikobytes.de on 13.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Basic configuration of the core system
#  * Install of basic dependencies
#  * Create new user, copy an ssh key to the remote host and add the user to sudoers
#  * Set iptables
---
  - name: Upgrade all packages to latest version (dist-upgrade)
    apt:
      upgrade: dist
      update_cache: yes
    become: yes

  - name: Install basic admin tools
    apt:
      name: [vim, sudo, mc, git]
    become: yes

  #
  # Create custom user and allow only him to acces via ssh
  #
  - name: "Create user {{ custom_remote_user }}"
    user:
      name: "{{ custom_remote_user }}"
      groups: sudo
      append: yes
      shell: /bin/bash
    become: yes

  - name: "Set authorized key for user {{ custom_remote_user }}"
    ansible.posix.authorized_key:
      user: "{{ custom_remote_user }}"
      state: present
      key: '{{ item }}'
    with_file:
      - id_rsa_slub.pub
    become: yes

  - name: Set correct ownership for password directory
    file:
      path: "/home/{{ custom_remote_user }}/.ssh"
      owner: "{{ custom_remote_user }}"
      group: "{{ custom_remote_user }}"
    become: yes

  - name: Replace sudoers
    copy:
      src: ./files/sudoers
      dest: /etc/sudoers
      owner: root
      group: root
      mode: "u=r,g=r"
    become: yes

  # Make sure certificates are installed
  - include_role:
      name:
        role: '../_roles/iptables'