# Created by jacob.mendt@pikobytes.de on 26.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
---
- name: restart postgresql
  become: yes
  service: name=postgresql state=restarted

- name: reload postgresql
  become: yes
  service: name=postgresql state=reloaded