# Created by jacob.mendt@pikobytes.de on 13.10.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
#
# Basic configuration of the core system
#  * Install of apache-http and configure apache as a reverse proxy
#  * Install a cronjob for cleaning the cache every minute
---
  - name: Upgrade all packages to latest version (dist-upgrade)
    apt:
      upgrade: dist
      update_cache: yes
    become: yes

  - name: Install apache2
    apt:
      name: [apache2]
    become: yes

  #
  # Setting up apache and the reverse proxy rules
  #
  - name: Enable mod_proxy, mod_proxy_http, mod_headers, mod_cache, mod_cache_disk mod_expires
    shell: a2enmod proxy proxy_http headers cache cache_disk expires
    become: yes

  - name: Remove all apache sites-enabled
    shell: rm -f /etc/apache2/sites-enabled/*
    become: yes

  - name: Remove all apache sites-enabled
    shell: rm -f /etc/apache2/sites-available/*
    become: yes

  - name: Copy configurations to sites-available
    template:
      src: 000-default.conf.j2
      dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
    with_items:
      - "{{ apache2.vhosts }}"
    become: yes

  - name: Enable apache sites
    shell:
      cmd: "a2ensite {{ item.name }}"
    with_items:
      - "{{ apache2.vhosts }}"
    become: yes

  - name: Restart apache2
    shell: systemctl restart apache2
    become: yes

  #
  # Configure htcacheclean for managing the cache size
  #

  - name: Create a cron job for htcacheclean
    cron:
      name: "Check disk cache"
      minute: "*/1"
      job: "htcacheclean -p /var/cache/apache2/mod_cache_disk/ -l {{ disk_cache_size }} -n -t "
      user: root
    become: yes