# Created by jacob.mendt@pikobytes.de on 15.12.21
#
# This file is subject to the terms and conditions defined in file
# "LICENSE", which is part of this source code package
---
- name: Install the `iptables` package
  package:
    name: iptables
    state: latest
  become: yes

- name: Flush existing firewall rules
  iptables:
    flush: true
  become: yes

- name: Firewall rule - allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: yes

- name: Firewall rule - allow established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Firewall rule - allow port ping traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
  become: yes

- name: Firewall rule - allow port 22/SSH traffic
  iptables:
    chain: INPUT
    destination_port: 22
    jump: ACCEPT
    protocol: tcp
  become: yes

- name: Firewall rule - allow port 80/HTTP traffic
  iptables:
    chain: INPUT
    destination_port: 80
    jump: ACCEPT
    protocol: tcp
  become: yes

- name: Firewall rule - allow port 443/HTTPS traffic
  iptables:
    chain: INPUT
    destination_port: 443
    jump: ACCEPT
    protocol: tcp
  become: yes

- name: Firewall rule - drop any traffic without rule
  iptables:
    chain: INPUT
    jump: DROP
  become: yes

- name: Install `netfilter-persistent` && `iptables-persistent` packages
  package:
    name: "{{item}}"
    state: present
  with_items:
   - iptables-persistent
   - netfilter-persistent
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
  become: yes

- name: save iptables
  shell: netfilter-persistent save
  become: yes